export const theme = {
  colors: {
    primary: '#1e3c72',
    secondary: '#2a5298',
    success: '#52c41a',
    warning: '#faad14',
    error: '#f5222d',
    white: '#ffffff',
    black: '#000000',
    gray: '#d9d9d9',
    lightGray: '#f0f0f0',
    darkGray: '#8c8c8c',
    background: '#f5f5f5',
    card: '#ffffff',
    border: '#d9d9d9',
    text: '#000000',
    textSecondary: '#595959',
    textLight: '#8c8c8c',
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
    xxl: 48,
  },
  borderRadius: {
    sm: 4,
    md: 8,
    lg: 12,
    xl: 16,
    round: 999,
  },
  fontSize: {
    xs: 12,
    sm: 14,
    md: 16,
    lg: 18,
    xl: 20,
    xxl: 24,
    xxxl: 32,
  },
  shadows: {
    small: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 2,
    },
    medium: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.15,
      shadowRadius: 8,
      elevation: 4,
    },
    large: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.2,
      shadowRadius: 16,
      elevation: 8,
    },
  },
};